[package]
name = "cards-play"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
# readme = "README.md"
license.workspace = true


[dependencies]

# ark-ec.workspace = true
# ark-ff.workspace = true
ark-serialize.workspace = true
ark-std.workspace = true
ark-secp256k1.workspace = true

# ark-transcript.workspace = true
# thiserror.workspace = true

getrandom_or_panic.workspace = true

cards-deck.workspace = true
cards-proofs.workspace = true
cards-protocol.workspace = true
deck-secp256k1.workspace = true
ez-serialize.workspace = true

serde = { workspace = true, optional = true }
ark-serde-compat = { workspace = true, optional = true }
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
anyhow = "1.0.55"


[lib]
crate-type = ["rlib", "cdylib"]


[features]
default = ["std"]
std = ["ark-std/std", "ark-serialize/std", "cards-deck/std", "wasm-bindgen?/std"]
# "ark-ec/std", "ark-ff/std", 
serde = ["dep:serde", "dep:ark-serde-compat"]
wasm-bindgen = ["serde", "dep:wasm-bindgen"]


