[package]
name = "cards-proofs"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
license = "MIT OR Apache-2.0"


[dependencies]
ark-ec.workspace = true
ark-ff.workspace = true
ark-serialize.workspace = true
ark-std.workspace = true

ark-transcript.workspace = true

thiserror.workspace = true

# TODO:  Where should this go?
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# [target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
# getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]
rand.workspace = true
ark-secp256k1.workspace = true
criterion = "0.3"
wasm-bindgen-test = "0.3.29"

[features]
default = ["std"]
std = ["ark-std/std", "ark-ec/std", "ark-ff/std", "ark-serialize/std", "ark-transcript/std"]

[[bench]]
name = "shuffle"
harness = false
