[package]
name = "deck-secp256k1"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
# readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]

ark-ec.workspace = true
ark-ff.workspace = true
ark-secp256k1.workspace = true

cards-proofs.workspace = true
cards-protocol.workspace = true
cards-deck = { workspace = true, features = [ "cards-proofs" ] }

[dev-dependencies]
ark-transcript.workspace = true
cards-protocol.workspace = true 

[features]
default = ["std"]
std = ["ark-ec/std", "ark-ff/std", "ark-secp256k1/std", "cards-deck/std"] # "cards-proofs/std", "cards-protocol/std"

